### ISSUE TITLE
Doesn't work with system.components config. 

### ISSUE THREAD

**Issue by zendevil** [jumblerg/ring-cors#5]
I have the following system.components config:

```
(defn config []
  {:http-port  (Integer. (or (env :port) 5000))
   :middleware [[wrap-defaults api-defaults]
                wrap-with-logger
                wrap-gzip
                ignore-trailing-slash
                [wrap-reload {:dir "../../src"}]
                [wrap-trace :header :ui]
                wrap-params
                wrap-keyword-params
                wrap-cookies
                [wrap-cors #".*"]
                ]})
```

But when my server makes a redirect, I still get the cors error on the client side.

**Comment by jumblerg** [comment]
a couple years later: i'm unfamiliar with system.components, but i imagine that, if the library properly implements the middleware contract, it should work here also.  there's not enough information for me to reproduce the redirect bug, however.

 there's a decent chance that the issue you were having was caused by your handler getting invoked by the preflight's OPTIONS request.  since the `3.0.0` release immediately returns preflight requests without calling any downstream middlewares, this may resolve the issue.
