### ISSUE TITLE
How to handle preflight requests down the pipeline?

### ISSUE THREAD

**Issue by egg-juxt** [jumblerg/ring-cors#7]
Hi, thanks for this neat library.

`wrap-cors` always propagates the preflight request to be handled down the pipeline. Usually, you just want to provide an empty 204. But, in order to do this, I will need to check that the request is a preflight request again in my own code, and, in any case, my response status will be overwritten by `wrap-cors` to a 200.

How are we meant to handle those preflight requests?

**Comment by jumblerg** [comment]
yw!

the expected behavior of `wrap-cors` is to intercept and immediately return the browser's preflight requests without exposing any of your downstream functions to them.  handlers further down the pipeline, including your own code, should never see the preflight and consequently have no logical dependency on the wrapper.

if they are, you may want to verify that `wrap-cors` is the outside/before any of your http-dependent code in your pipeline. it should look something like this:
```
(-> handle-request (wrap-foo) (wrap-bar) (wrap-cors identity))
```

let me know if this helps.

**Comment by egg-juxt** [comment]
Thanks for your response!

> the expected behavior of wrap-cors is to intercept and immediately return the browser's preflight requests without exposing any of your downstream functions to them

That isn't my experience, and I don't see how that can be by watching the code, which calls the downstream handler unconditionally:
```
(defn allow-origins [req handler & [allow :as orig-regxps]]
  (let [req-hmap (req :headers)
        req-orig (req-hmap "origin")
        allow-fn #(some (fn [x] (guard (re-matches x %1))) %2)
        mergeh   #(update %1 :headers (comp clean merge) (cors-hdrs req-hmap) %2)
        cors-ok? (if (fn? allow) (allow req-orig) (allow-fn req-orig orig-regxps))
        pflt-ok? (and cors-ok? (= (get req :request-method) :options))]
    (let [res (handler req)] <--- here
      (cond pflt-ok? (-> res (assoc :status 200) (mergeh (pflt-hdrs req-hmap)))
            cors-ok? (->> res ((juxt identity stnd-hdrs)) (apply mergeh))
            :else    res))))
```

**Comment by jumblerg** [comment]
you're right: apologies for the fud.  it's been 8 years.

it does now, though!

give it a try and let me know how well this approach works.  i haven't done any testing yet, so a bit of help here would be appreciated.

**Comment by egg-juxt** [comment]
It is working nicely now, thanks!

What is your policy around versions? Would you do a final "3.0.0"?

**Comment by jumblerg** [comment]
you're welcome!

i believe there was some rationale for passing the preflight down the pipeline instead of swallowing it (my own services were merely ignoring the OPTIONS requests), but i forget what it might have been...

my policy is that, if someone tells me it works, i push it to clojars.  :D

standby for `3.0.0`.

**Comment by jumblerg** [comment]
`3.0.0` deployed.
